from pandasdb.communication.errors.base import PandasDBException


class PandasDBIOExeption(PandasDBException):
    pass
